### PR TITLE
Licence

### PR DESCRIPTION
**Pull request by claytonk2**

### CODE REVIEW

**Review by alemon-aquaveo — CHANGES_REQUESTED** [review]
You need to rebase with master and redo the pull request.

**Comment by claytonk2** [comment]
This has been rebased with master.

**Comment by Tsubashi** [comment]
Commit messages that do not describe the changes (such as ‘a’) are unacceptable. Please amend the commit message to complete the sentence “If merged, this commit will...”

**Comment by claytonk2** [comment]
I changed the commit names.

**Review by alemon-aquaveo — APPROVED** [review]

**Comment by gagelarsen** [comment]
fixed elsewhere

**Pull request closed without merging**
